### ISSUE TITLE
Add mindmap Scripts Problem

### ISSUE THREAD

**Issue by XuanNui** [Bowen-0x00/obsidian-excalidraw-scripts#1]
1.brat https://github.com/Bowen-0x00/obsidian-excalidraw-plugin-ymjr 已经更新到最新版本
我的问题汇总
1.使用excalidraw add mindmap 组件后,当我删除一个元素,再按TAB 或者enter 思维导图模式失效
2. 当我删除一个元素后,不能再删除excalidraw的另外元素
3. 小好问题,箭头如何回归好看,像您的第一个视频
![1](https://github.com/Bowen-0x00/obsidian-excalidraw-scripts/assets/104402409/a0fa2f4f-42ce-49c4-85cd-c04586de6575)
![2](https://github.com/Bowen-0x00/obsidian-excalidraw-scripts/assets/104402409/c2f00635-1760-4ffe-9a28-51c992284377)
![3](https://github.com/Bowen-0x00/obsidian-excalidraw-scripts/assets/104402409/48ecba13-59eb-48d4-94d6-6f74ace6bb02)

**Comment by Bowen-0x00** [comment]
@XuanNui 稍后我更新脚本来解决这个问题；你指的箭头更好看是指的什么？箭头的箭头形状、阴影、曲线的位置

**Comment by Bowen-0x00** [comment]
![image](https://github.com/Bowen-0x00/obsidian-excalidraw-scripts/assets/120435922/6df4881c-f531-4011-bdd3-a296f6a07f1a)
@XuanNui  之后更新会调整曲线形状

**Comment by XuanNui** [comment]
不好意思啊,所有问题已经解决.
是我自己尝试的不够,新建ob新的库,并只留下您提供的mindmap脚本库,就解决这个问题了
至于美观我的意思是,两个地方:
- [X] 1这次自动这样了
![image](https://github.com/Bowen-0x00/obsidian-excalidraw-scripts/assets/104402409/319d7beb-37c4-4458-8d0c-b5fef59cdb50)

2.还有箭头的形状,或许可以更好看,至于是否更改看您心情
![image](https://github.com/Bowen-0x00/obsidian-excalidraw-scripts/assets/104402409/72518dca-685f-44c7-8691-2e3c19def7e5)
