### ISSUE TITLE
[功能增强]增加替换标签和删除标签功能

### ISSUE THREAD

**Issue by PennHui666** [Bowen-0x00/obsidian-excalidraw-scripts#2]
删除标签虽然可以通过删除元素实现但是有些元素不想删除时就不行了
替换标签虽然可以进入源文件修改但是太麻烦了

**Comment by Bowen-0x00** [comment]
@PennHui666 目前可以再次运行脚本来修改，而删除是因为脚本做了判断为空时返回所以没删除，可以通过输入为 "," 然后保存来删除。我稍后更新下脚本，为空时不再返回。
